# Generated by Django 6.0.7 on 2026-08-23 03:37

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('document', tinymce.models.HTMLField()),
                ('category', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('document', tinymce.models.HTMLField()),
                ('author', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='CaseManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('document', tinymce.models.HTMLField()),
                ('type', models.CharField(choices=[('LAWS OF BANGLADESH', 'Laws of Bangladesh'), ('APPEllAtE DIVISION', 'Appellate Division'), ('DIGEST', 'Digest'), ('HIGH COURT DIVISION', 'High Court Division'), ('LITIGATION', 'Litigation')], default='LAWS OF BANGLADESH', max_length=1000)),
                ('category', models.CharField(max_length=400)),
                ('sub_category', models.CharField(default='none', max_length=400)),
                ('Year', models.CharField(default='none', max_length=255)),
            ],
            options={
                'verbose_name': 'Case Management',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('logo', models.ImageField(upload_to='client_logos/')),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('telephones', models.TextField()),
                ('cell', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConventionAndTreaties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('document', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('document', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentationsAndLitigations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('document', tinymce.models.HTMLField()),
                ('type', models.CharField(choices=[('DOCUMENTATION', 'documentation'), ('LEGAL OPINION', 'Legal Opinion'), ('LITIGATION', 'Litigation')], default='DOCUMENTATION', max_length=1000)),
                ('category', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Document and Litigation',
                'verbose_name_plural': 'Documents and Litigation',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LegalCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('document', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('document', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='social_media_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('video_url', models.URLField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
