# Generated by Django 6.0.7 on 2026-08-23 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0002_alter_articles_id_alter_books_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='FeedBack',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
