# Generated by Django 6.0.7 on 2026-08-23 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0003_delete_clients_delete_contact_delete_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='published_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
