# Generated by Django 6.0.7 on 2026-08-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0004_articles_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcourses',
            name='type',
            field=models.CharField(default='none', max_length=400),
        ),
    ]
