# Generated by Django 6.0.7 on 2026-08-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0005_legalcourses_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerials',
            name='type',
            field=models.CharField(default='none', max_length=400),
        ),
    ]
