# Generated by Django 6.0.7 on 2026-08-27 09:39

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0006_coursematerials_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', tinymce.models.HTMLField()),
            ],
        ),
    ]
