# Generated by Django 6.0.7 on 2026-08-29 06:44

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0007_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('document', tinymce.models.HTMLField()),
            ],
        ),
    ]
