# Generated by Django 6.0.7 on 2026-09-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0008_career'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseManagement',
        ),
    ]
