# Generated by Django 6.0.7 on 2026-09-05 08:52

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0010_case_digest_law'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('case_no', models.CharField(max_length=100)),
                ('judge', models.CharField(blank=True, max_length=255, null=True)),
                ('advocate', models.CharField(blank=True, max_length=255, null=True)),
                ('citation', models.CharField(blank=True, max_length=255, null=True)),
                ('case_year', models.PositiveIntegerField()),
                ('appellant', models.CharField(max_length=255, verbose_name='Appellant')),
                ('respondent', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('court', models.CharField(max_length=255)),
                ('document', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-case_year', '-delivery_date'],
            },
        ),
    ]
