# Generated by Django 6.0.7 on 2026-09-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0011_journal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-case_year', '-delivery_date'], 'verbose_name': 'Journal', 'verbose_name_plural': 'Journals'},
        ),
        migrations.AddField(
            model_name='journal',
            name='month',
            field=models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], default='JANUARY', max_length=1000),
        ),
    ]
