# Generated by Django 6.0.7 on 2026-09-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0012_alter_journal_options_journal_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Articles ', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Books ', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='conventionandtreaties',
            options={'verbose_name': 'Conventions and Treaties', 'verbose_name_plural': 'Conventions and Treaties'},
        ),
        migrations.AlterModelOptions(
            name='coursematerials',
            options={'verbose_name': 'Course Materials', 'verbose_name_plural': 'Course Materials'},
        ),
        migrations.AlterModelOptions(
            name='legalcourses',
            options={'verbose_name': 'Legal Courses', 'verbose_name_plural': 'Legal Courses'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
    ]
