# Generated by Django 6.0.7 on 2026-09-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0013_alter_aboutus_options_alter_articles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='division',
            field=models.CharField(default='', max_length=255),
        ),
    ]
