# Generated by Django 6.0.7 on 2026-09-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0014_alter_case_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digest',
            name='subtype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
