# Generated by Django 6.0.7 on 2026-09-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0015_alter_digest_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digest',
            name='appellant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Appellant'),
        ),
        migrations.AlterField(
            model_name='digest',
            name='case_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='digest',
            name='case_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digest',
            name='court',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='digest',
            name='respondent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
