# Generated by Django 6.0.7 on 2026-08-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_carousel_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersOf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='members_of_images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
