# Generated by Django 6.0.7 on 2026-08-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_membersof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='client_description',
            field=models.CharField(default='text client who does testing', max_length=1000),
        ),
    ]
