# Generated by Django 6.0.7 on 2026-08-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_remove_feedback_name_feedback_client_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CHAMBER', 'Chamber'), ('CONFERENCE', 'Conference & Seminars'), ('LNJ_TEAM', 'LNJ Team'), ('OTHERS', 'Others')], default='OTHERS', max_length=50),
        ),
    ]
