# Generated by Django 6.0.7 on 2026-08-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LAWYER', 'Lawyer'), ('CLIENT', 'Client'), ('ADMIN', 'Admin'), ('STAFF', 'Staff')], default='CLIENT', max_length=10),
        ),
    ]
