# Generated by Django 6.0.7 on 2026-08-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='lawyer_photo',
            field=models.ImageField(blank=True, help_text='Upload official lawyer photo', null=True, upload_to='lawyer_photos/'),
        ),
    ]
