# Generated by Django 6.0.7 on 2026-08-23 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_articles_books_casemanagement_clients_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='CaseManagement',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ConventionAndTreaties',
        ),
        migrations.DeleteModel(
            name='CourseMaterials',
        ),
        migrations.DeleteModel(
            name='DocumentationsAndLitigations',
        ),
        migrations.DeleteModel(
            name='FeedBack',
        ),
        migrations.DeleteModel(
            name='LegalCourses',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
