# Generated by Django 6.0.7 on 2026-08-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_articles_delete_books_delete_casemanagement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='designation',
            field=models.CharField(default='associate', max_length=1000),
        ),
    ]
