# Generated by Django 6.0.7 on 2026-08-28 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_lawyerprofile_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'LAWYER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
