# Generated by Django 6.0.7 on 2026-09-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the booking was made', null=True),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='notes_from_client',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
    ]
