# Generated by Django 6.1.1 on 2026-09-12 08:51

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='office_location',
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='bio',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
