"""
Django settings for LawyersAndJurits project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3+bgwl-b!fwuqm^+wgu3@mf@=+059zb0d=hj^7gzilkk#$p4$a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

AUTH_USER_MODEL = "main.User"


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Application definition

INSTALLED_APPS = [
    "unfold",
          'tinymce',  # Must be before django.contrib.admin
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    'main.apps.MainConfig',
    'visual.apps.VisualConfig',
    'interface.apps.InterfaceConfig',
    'auth.apps.AuthConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'corsheaders',
 
]


UNFOLD = {
    "SITE_HEADER": "Lawyers And Jurits Admin",  # Replaces "Django administration" in the sidebar/top
    "SITE_TITLE": "Lawyers And Jurits",       # Replaces the suffix in the browser <title> tag
    "SITE_SUBHEADER": "Welcome Dashboard", 

    "COLORS": {
    "primary": {
        "50": "oklch(97.5% 0.015 85)",
        "100": "oklch(94.0% 0.030 85)",
        "200": "oklch(87.5% 0.055 84)",
        "300": "oklch(79.5% 0.075 83)",
        "400": "oklch(70.5% 0.090 82)",
        "500": "oklch(62.0% 0.100 81)",
        "600": "oklch(54.0% 0.095 80)",
        "700": "oklch(46.0% 0.085 79)",
        "800": "oklch(38.5% 0.070 78)",
        "900": "oklch(32.0% 0.055 77)",
        "950": "oklch(23.5% 0.040 76)",
    },
    "base": {
        "50": "oklch(98.0% 0.002 90)",
        "100": "oklch(95.5% 0.003 90)",
        "200": "oklch(90.0% 0.004 90)",
        "300": "oklch(82.0% 0.005 90)",
        "400": "oklch(70.0% 0.006 90)",
        "500": "oklch(58.0% 0.006 90)",
        "600": "oklch(47.0% 0.006 90)",
        "700": "oklch(37.0% 0.006 90)",
        "800": "oklch(27.0% 0.006 90)",
        "900": "oklch(18.0% 0.006 90)",
        "950": "oklch(11.0% 0.005 90)",
    },
},   # Optional subheader text below the header
}


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

       "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    "AUTH_HEADER_TYPES": ("Bearer",),
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

TINYMCE_DEFAULT_CONFIG = {
    "height": "1000px",
    "width": "100%",
    "menubar": "file edit view insert format tools table help",
    "license_key": "gpl",
    "plugins": (
        "advlist autolink lists link image charmap print preview anchor "
        "searchreplace visualblocks code fullscreen insertdatetime media table "
        "paste wordcount"
    ),
    "toolbar": (
        "undo redo | formatselect | bold italic backcolor | "
        "alignleft aligncenter alignright alignjustify | "
        "bullist numlist outdent indent | image code | removeformat | help"
    ),
    "custom_undo_redo_levels": 10,
    "images_upload_url": "/api/upload-image/",
    "automatic_uploads": True,
    "images_reuse_filename": True,
  
    # --- FIX CONFIGURATION HERE ---
    "selector": "textarea",
    "convert_urls": True,          # Let TinyMCE control URL processing
    "relative_urls": False,        # DO NOT convert to relative paths
    "remove_script_host": False,   # DO NOT strip out the domain or host IP
    "document_base_url": "http://10.0.2.2:8000/"  # The forced fallback root
}


ROOT_URLCONF = 'LawyersAndJurits.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LawyersAndJurits.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = [
    'https://*.trycloudflare.com',
]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',  # Critical for SimpleJWT Bearer tokens
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
